# Generated by Django 5.0.4 on 2024-05-17 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExcelData',
            new_name='HistoricoVulnerabilidadesFortify',
        ),
    ]
